name: Build and deploy Node.js backend to Azure Web App - Notes-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install and build frontend (optional)
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client/src

      - name: Build frontend
        run: npm run build
        working-directory: ./client/src

      # Install backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./server

      # Optional: test backend
      - name: Test backend
        run: npm run test --if-present
        working-directory: ./server

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Notes-app'
          slot-name: 'Production'
          package: .
